//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusComplaintPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complaintmaster
    {
        public int Id { get; set; }
        public string FacilityType { get; set; }
        public string Location { get; set; }
        public string IssueDetails { get; set; }
        public string ImageFile { get; set; }
        public string Status { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int StudentId { get; set; }
        public string ComplaintNo { get; set; }
    
        public virtual registermaster registermaster { get; set; }
    }
}
