//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusComplaintPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationmaster
    {
        public int NotiId { get; set; }
        public string Message { get; set; }
        public System.DateTime AddedOn { get; set; }
    }
}
